/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./HydroPulse-Map-Simulation/src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#00d9ff",
        "surface-container-high": "#272a30",
        "outline": "#859398",
        "tertiary-fixed": "#ffdea9",
        "primary": "#afecff",
        "surface-container": "#1d2025",
        "inverse-on-surface": "#2d3036",
        "error-container": "#93000a",
        "outline-variant": "#3c494d",
        "on-secondary": "#002681",
        "primary-fixed-dim": "#00d9ff",
        "surface-container-low": "#181c21",
        "surface-bright": "#36393f",
        "on-primary-container": "#005b6c",
        "on-primary-fixed-variant": "#004e5d",
        "on-primary-fixed": "#001f26",
        "surface-variant": "#32353b",
        "tertiary": "#ffdeaa",
        "on-tertiary-container": "#6e4d00",
        "on-secondary-fixed": "#001551",
        "background": "#101419",
        "error": "#ffb4ab",
        "on-surface": "#e0e2ea",
        "tertiary-fixed-dim": "#febb29",
        "inverse-surface": "#e0e2ea",
        "on-tertiary-fixed": "#271900",
        "primary-fixed": "#aeecff",
        "inverse-primary": "#00687b",
        "secondary-container": "#023dbf",
        "on-surface-variant": "#bbc9ce",
        "on-primary": "#003641",
        "secondary": "#b7c4ff",
        "on-tertiary-fixed-variant": "#5e4100",
        "surface-dim": "#101419",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#ffbb2a",
        "surface": {
          DEFAULT: '#101419',
          dim: '#05070A',
          black: '#050505',
          container: '#1d2025',
          high: '#272a30',
          higher: '#32353b',
        },
        "on-tertiary": "#422d00",
        "on-background": "#e0e2ea",
        "on-error": "#690005",
        "secondary-fixed-dim": "#b7c4ff",
        "secondary-fixed": "#dce1ff",
        "surface-container-lowest": "#0b0e13",
        "on-secondary-container": "#a8b9ff",
        "primary-container": "#00d9ff",
        "on-secondary-fixed-variant": "#0039b5",
        "surface-container-highest": "#32353b",
        accent: {
          cyan: '#00D9FF',
          'cyan-dim': 'rgba(0, 217, 255, 0.15)',
          violet: '#5B7FFF',
          amber: '#FFB02A',
          red: '#FF3B3B',
        },
        text: {
          primary: '#E0E2EA',
          muted: '#878A8F',
          subtle: '#555A64',
        },
      },
      spacing: {
        "gutter-desktop": "24px",
        "space-xs": "8px",
        "space-xl": "32px",
        "margin-desktop": "48px",
        "space-2xs": "4px",
        "space-sm": "12px",
        "space-lg": "24px",
        "margin-mobile": "20px",
        "space-2xl": "48px",
        "grid-unit": "4px",
        "space-md": "16px",
        "space-3xl": "64px",
        "gutter-mobile": "16px",
        "space-4xl": "96px",
      },
      fontFamily: {
        faculty: ['"Faculty Glyphic"', 'sans-serif'],
        clash: ['"Clash Grotesk"', 'sans-serif'],
        "telemetry-mono-lg": ['Lexend', 'sans-serif'],
        "display-hero": ['"Space Grotesk"', 'sans-serif'],
        "body-lg": ['Metrophobic', 'sans-serif'],
        space: ['"Space Grotesk"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
        sans: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        'hud-cyan': '0 0 20px rgba(0, 217, 255, 0.2), inset 0 0 15px rgba(0, 217, 255, 0.1)',
        'hud-glow': '0 0 30px rgba(0, 217, 255, 0.35)',
      },
    },
  },
  plugins: [],
};
